// PROPOSED data model for BizPilot — a starting design derived from the
// requirements, for review before any table is created. Nothing here exists yet.
// Tables are named for what BizPilot stores, never for a vendor it talks to.
// Money is whole kobo (integer) so every calculation is exact and server-side (REQ-015).
// `serves` lists requirement ids; the Data model tab joins them to plan.json at runtime.
window.CC_DATA_MODEL = {
  tables: [
    {
      name: 'tenant',
      purpose: 'One business using BizPilot. Every business record belongs to exactly one tenant.',
      serves: ['REQ-008', 'REQ-011'],
      fields: [
        { name: 'id', type: 'uuid', note: 'Primary key.' },
        { name: 'business_name', type: 'text' },
        { name: 'created_at', type: 'timestamptz' },
      ],
    },
    {
      name: 'app_user',
      purpose: 'A person who signs in: owner, staff, administrator, compliance officer or analyst.',
      serves: ['REQ-008', 'REQ-010'],
      fields: [
        { name: 'id', type: 'uuid', note: 'Primary key; the user ID written to every audit record.' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'full_name', type: 'text' },
        { name: 'phone', type: 'text' },
        { name: 'role', type: 'text', note: 'owner | staff | admin | compliance | analyst.' },
        { name: 'created_at', type: 'timestamptz' },
      ],
    },
    {
      name: 'supplier',
      purpose: 'Who a product is bought from.',
      serves: ['REQ-006'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'name', type: 'text' },
        { name: 'phone', type: 'text' },
      ],
    },
    {
      name: 'product',
      purpose: 'Something the business sells, with its stock and prices.',
      serves: ['REQ-006', 'REQ-018'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'supplier_id', type: 'uuid', ref: 'supplier', note: 'Nullable.' },
        { name: 'name', type: 'text' },
        { name: 'quantity_on_hand', type: 'integer' },
        { name: 'buying_price_kobo', type: 'bigint' },
        { name: 'selling_price_kobo', type: 'bigint', note: 'Profit margin is calculated server-side from the two prices, not stored.' },
        { name: 'reorder_level', type: 'integer', note: 'Below this, the product is low stock.' },
      ],
    },
    {
      name: 'customer',
      purpose: 'Someone the business sells to, and may be owed money by.',
      serves: ['REQ-009', 'REQ-013'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'name', type: 'text' },
        { name: 'whatsapp_number', type: 'text', note: 'Nullable; without it a message cannot be sent and the failure is logged.' },
        { name: 'created_at', type: 'timestamptz' },
      ],
    },
    {
      name: 'business_transaction',
      purpose: 'A sale, expense or purchase, however it was entered — text, voice or form.',
      serves: ['REQ-001', 'REQ-002', 'REQ-016'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'recorded_by', type: 'uuid', ref: 'app_user' },
        { name: 'customer_id', type: 'uuid', ref: 'customer', note: 'Nullable.' },
        { name: 'kind', type: 'text', note: 'sale | expense | purchase.' },
        { name: 'entry_method', type: 'text', note: 'text | voice | form.' },
        { name: 'raw_input', type: 'text', note: 'What the user typed or said, kept for audit.' },
        { name: 'total_kobo', type: 'bigint', note: 'Calculated server-side from the lines.' },
        { name: 'occurred_at', type: 'timestamptz' },
        { name: 'created_at', type: 'timestamptz' },
      ],
    },
    {
      name: 'transaction_line',
      purpose: 'One product and quantity within a transaction.',
      serves: ['REQ-001', 'REQ-006'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'transaction_id', type: 'uuid', ref: 'business_transaction' },
        { name: 'product_id', type: 'uuid', ref: 'product' },
        { name: 'quantity', type: 'integer' },
        { name: 'unit_price_kobo', type: 'bigint' },
      ],
    },
    {
      name: 'stock_movement',
      purpose: 'Every change to a product’s quantity, with who made it and why.',
      serves: ['REQ-006'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'product_id', type: 'uuid', ref: 'product' },
        { name: 'transaction_id', type: 'uuid', ref: 'business_transaction', note: 'Nullable for manual adjustments.' },
        { name: 'change', type: 'integer', note: 'Negative for a sale, positive for a restock.' },
        { name: 'reason', type: 'text' },
        { name: 'recorded_by', type: 'uuid', ref: 'app_user' },
        { name: 'created_at', type: 'timestamptz' },
      ],
    },
    {
      name: 'customer_debt',
      purpose: 'Money a customer owes, and how much has been paid back.',
      serves: ['REQ-009'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'customer_id', type: 'uuid', ref: 'customer' },
        { name: 'transaction_id', type: 'uuid', ref: 'business_transaction' },
        { name: 'amount_kobo', type: 'bigint' },
        { name: 'paid_kobo', type: 'bigint' },
        { name: 'due_on', type: 'date' },
        { name: 'status', type: 'text', note: 'open | settled | written_off.' },
      ],
    },
    {
      name: 'reminder_rule',
      purpose: 'A tenant’s settings for automatic debt reminders.',
      serves: ['REQ-017'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'days_overdue', type: 'integer' },
        { name: 'minimum_amount_kobo', type: 'bigint', note: 'Debts below this get no reminder.' },
        { name: 'channel', type: 'text', note: 'whatsapp | sms.' },
        { name: 'active', type: 'boolean' },
        { name: 'updated_by', type: 'uuid', ref: 'app_user' },
        { name: 'updated_at', type: 'timestamptz' },
      ],
    },
    {
      name: 'outbound_message',
      purpose: 'A message sent (or attempted) to a customer — reminders and notifications.',
      serves: ['REQ-009', 'REQ-013'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'customer_id', type: 'uuid', ref: 'customer' },
        { name: 'debt_id', type: 'uuid', ref: 'customer_debt', note: 'Nullable.' },
        { name: 'channel', type: 'text' },
        { name: 'idempotency_key', type: 'text', note: 'Unique; a retry cannot send twice.' },
        { name: 'status', type: 'text', note: 'queued | sent | failed.' },
        { name: 'provider_message_id', type: 'text', note: 'Nullable.' },
        { name: 'error', type: 'text', note: 'Nullable; why it failed.' },
        { name: 'sent_by', type: 'uuid', ref: 'app_user' },
        { name: 'created_at', type: 'timestamptz' },
      ],
    },
    {
      name: 'ai_action',
      purpose: 'Every AI query, briefing and tool call — input, output, outcome — for audit.',
      serves: ['REQ-005', 'REQ-007', 'REQ-010', 'REQ-014'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'user_id', type: 'uuid', ref: 'app_user' },
        { name: 'action_type', type: 'text', note: 'query | briefing | tool.' },
        { name: 'input', type: 'jsonb' },
        { name: 'output', type: 'jsonb', note: 'Nullable if it failed.' },
        { name: 'model', type: 'text' },
        { name: 'status', type: 'text', note: 'succeeded | failed.' },
        { name: 'error', type: 'text', note: 'Nullable; error details on failure.' },
        { name: 'created_at', type: 'timestamptz' },
      ],
    },
    {
      name: 'daily_briefing',
      purpose: 'The AI’s morning summary for a tenant: sales, profit, debts, and what data was missing.',
      serves: ['REQ-014'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'briefing_date', type: 'date' },
        { name: 'content', type: 'text' },
        { name: 'missing_data', type: 'jsonb', note: 'What the briefing could not cover.' },
        { name: 'ai_action_id', type: 'uuid', ref: 'ai_action' },
      ],
    },
    {
      name: 'audit_event',
      purpose: 'Every data access, including denied cross-tenant attempts, dashboard views and financial calculations.',
      serves: ['REQ-008', 'REQ-015', 'REQ-003'],
      fields: [
        { name: 'id', type: 'uuid' },
        { name: 'tenant_id', type: 'uuid', ref: 'tenant' },
        { name: 'user_id', type: 'uuid', ref: 'app_user' },
        { name: 'event', type: 'text', note: 'e.g. data_access | access_denied | dashboard_view | calculation.' },
        { name: 'resource', type: 'text' },
        { name: 'allowed', type: 'boolean' },
        { name: 'detail', type: 'jsonb', note: 'e.g. transaction id and calculation inputs/result.' },
        { name: 'created_at', type: 'timestamptz' },
      ],
    },
  ],
};
